apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: node
        ports:
        - containerPort: 8080
